### ISSUE TITLE
[Bug] cannot seem to get verse over 100

### ISSUE THREAD

**Issue by sionirvine** [daniel-tran/meaningless#19]
### Summary of the problem
i was trying to extract / download the book of Psalms. noticed the extractor / downloader on chapter 119 is stopped on verse 100. trying to manually set passage_range, e.g `extractor.get_passage_range(book="NASB1995", chapter_from=119, chapter_to=119, passage_from=101, passage_to=176)` returns the chapter 119, **verse 100**.

### Expected Behaviour
should extract / download the required passage after 100.

### Steps to replicate the problem
- [x] create a new python project
- [x] install the meaningless python package.
- [x] add `from meaningless import WebExtractor`.
- [x] set up extractor
- [x] print the extractor result.

```python
from meaningless import WebExtractor

extract = WebExtractor(translation="NASB1995")
passage = extract.get_passage_range(book="Psalms", chapter_from=119, chapter_to=119, passage_from=101, passage_to=176)
print(passage)

# above code prints:
# ¹⁰⁰ I understand more than the aged,
# Because I have observed Your precepts.
```

### Environment
- Python version: 3.10.12
- Operating system: Linux (Ubuntu 22.04.3 LTS)
- Library version: 1.0.0

**Comment by daniel-tran** [comment]
Thanks for reporting this. I can replicate the issue on my environment and there is a fix staged as part of the 1.1.0 release (see https://github.com/daniel-tran/meaningless/commit/78612729a535b130b9185ce8eaf23a1759710f42).
