### ISSUE TITLE
change translation?

### ISSUE THREAD

**Issue by mvnaylor** [daniel-tran/meaningless#2]
I'm rather new to Python and, though I figured out most of the rest your app, I cannot find a way to change the translation. It always prints NIV. Am I able to pass it as a string for my simple python script?

**Comment by daniel-tran** [comment]
You can specify a different translation by simply passing in a parameter when you set up your extractor or downloader object.
Using the Web Extractor example from the README, this can look something like:

```python
from meaningless import WebExtractor

if __name__ == '__main__':
    bible = WebExtractor(translation='ESV')
    passage = bible.get_passage('Ecclesiastes', 1, 2)
    print(passage)
```

**Comment by mvnaylor** [comment]
This is perfect. Thank you!
